export const navItems = [
  { label: "实验室", labelEn: "Lab", sub: "LAB", href: "#lab" },
  { label: "作品", labelEn: "Works", sub: "WORKS", href: "#works" },
  { label: "关于", labelEn: "About", sub: "ABOUT", href: "#about" },
  { label: "联系", labelEn: "Contact", sub: "CONTACT", href: "#contact" },
];

type ShowcaseCategory = {
  id: string;
  index: string;
  cn: string;
  en: string;
  tone: string;
  headline: string;
  headlineCn: string;
  note: string;
  noteEn: string;
  /** 品牌归属 caption（"灵感来自 …" / "致敬 …"）— 自主作品的风格归属说明 */
  brand?: string;
  brandEn?: string;
  duration: string;
  coverSrc?: string;
  videoSrc?: string;
  previewImages?: string[];
};

export const showcaseCategories: ShowcaseCategory[] = [
  {
    id: "works-space-design",
    index: "01",
    cn: "地中海风格",
    en: "Mediterranean",
    tone: "space",
    headline: "Fashion Aesthetic",
    headlineCn: "时尚美学",
    note: "空间，被重新看见。",
    noteEn: "Space, reframed.",
    brand: "灵感来自地中海度假美学 · 致敬 Loro Piana / The Row 风格",
    brandEn: "Inspired by Mediterranean resort aesthetics · a nod to Loro Piana / The Row",
    duration: "02:09",
    coverSrc: "/covers/works-01.jpg",
    videoSrc: "/videos/fashion-01.mp4",
  },
  {
    id: "works-fashion",
    index: "02",
    cn: "电影主题",
    en: "Cinematic",
    tone: "fashion",
    headline: "Cocktail Edit",
    headlineCn: "潮流酒单",
    note: "材质。剪影。一帧之间。为品牌形象片而生。",
    noteEn: "Texture. Silhouette. One frame, built for brand films.",
    brand: "电影主题概念酒单 · 灵感来自影展酒会美学",
    brandEn: "A cinema-inspired cocktail concept",
    duration: "02:10",
    coverSrc: "/covers/works-02.jpg",
    previewImages: [
      "/galleries/works-02/page-01.jpg",
      "/galleries/works-02/page-02.jpg",
      "/galleries/works-02/page-03.jpg",
      "/galleries/works-02/page-04.jpg",
      "/galleries/works-02/page-05.jpg",
      "/galleries/works-02/page-06.jpg",
      "/galleries/works-02/page-07.jpg",
    ],
  },
  {
    id: "works-sportswear",
    index: "03",
    cn: "科幻越野",
    en: "Sci-Fi Off-Road",
    tone: "cyan",
    headline: "Auto Cinematic",
    headlineCn: "汽车主题",
    note: "速度。力量。线条。新品上线即用。",
    noteEn: "Speed. Force. Line. Drop-day ready.",
    brand: "灵感来自 Land Rover Defender 越野电影美学",
    brandEn: "Inspired by Defender-era off-road cinema",
    duration: "01:42",
    coverSrc: "/covers/works-03.jpg",
    videoSrc: "/videos/automotive.mp4",
  },
  {
    id: "works-auto",
    index: "04",
    cn: "城市晨跑",
    en: "Urban Running",
    tone: "blue",
    headline: "Running Aesthetic",
    headlineCn: "跑步美学",
    note: "光影与机械，毫厘之间。主片，或功能拆解。",
    noteEn: "Light and metal, millimeters apart. Hero film or feature cut.",
    brand: "致敬 Nike NYC 都市竞速美学",
    brandEn: "A tribute to Nike NYC race aesthetics",
    duration: "00:39",
    coverSrc: "/covers/works-04.jpg",
    videoSrc: "/videos/auto.mp4",
  },
  {
    id: "works-fmcg",
    index: "05",
    cn: "黄金时刻",
    en: "Golden Hour",
    tone: "fmcg",
    headline: "Portrait Texture",
    headlineCn: "人像质感",
    note: "包装的质感，节奏的呼吸。电商即投，社媒即发。",
    noteEn: "Packshot texture, social-feed rhythm. Ready for e-com and post.",
    brand: "灵感来自 Nike 意识流广告美学",
    brandEn: "Inspired by Nike's stream-of-consciousness film language",
    duration: "01:16",
    coverSrc: "/covers/works-05.jpg",
    videoSrc: "/videos/nike-outdoor.mp4",
  },
  {
    id: "works-yoga",
    index: "06",
    cn: "静谧瑜伽",
    en: "Quiet Yoga",
    tone: "fashion",
    headline: "Lifestyle Edit",
    headlineCn: "生活方式",
    note: "光线、呼吸、留白。把克制感拍成生活方式。",
    noteEn: "Light. Breath. Negative space. Restraint, lived in.",
    brand: "致敬 Alo Yoga / Lululemon 瑜伽美学",
    brandEn: "A tribute to Alo Yoga / Lululemon aesthetics",
    duration: "00:48",
    coverSrc: "/covers/works-yoga.jpg",
    videoSrc: "/videos/yoga.mp4",
  },
  {
    id: "works-nike",
    index: "07",
    cn: "越野跑者",
    en: "Trail Runner",
    tone: "orange",
    headline: "Outdoor Sport",
    headlineCn: "户外运动",
    note: "贴近肌理的速度感。短片封面，社媒首帧。",
    noteEn: "Speed at skin level. Short-film cover or social first frame.",
    brand: "灵感来自法国海岸 · 致敬 Salomon Trail Running 系列",
    brandEn: "Inspired by the French coast · a nod to Salomon Trail Running",
    duration: "00:55",
    coverSrc: "/covers/works-06.jpg",
    videoSrc: "/videos/nike.mp4",
  },
  {
    id: "works-salomon",
    index: "08",
    cn: "都市机能",
    en: "Urban Performance",
    tone: "cyan",
    headline: "Street Sport",
    headlineCn: "街头运动",
    note: "山野、风、步频。把功能感拍成情绪。",
    noteEn: "Trail. Wind. Cadence. Performance, felt.",
    brand: "致敬 Arc'teryx Veilance / ACRONYM 都市机能美学",
    brandEn: "A tribute to Arc'teryx Veilance / ACRONYM urban-tech aesthetics",
    duration: "00:36",
    coverSrc: "/covers/works-07.jpg",
    videoSrc: "/videos/salomon.mp4",
  },
  {
    id: "works-arcteryx",
    index: "09",
    cn: "瑜伽人像",
    en: "Yoga Portrait",
    tone: "blue",
    headline: "Sport Lifestyle",
    headlineCn: "运动生活",
    note: "高速雪线与冷色锋面。户外大片的开场。",
    noteEn: "Fast snow lines, cold-front edges. An outdoor film's opening shot.",
    brand: "灵感来自 Alo Yoga 居家系列",
    brandEn: "Inspired by the Alo Yoga in-studio series",
    duration: "00:45",
    coverSrc: "/covers/works-08.jpg",
    videoSrc: "/videos/arcteryx.mp4",
  },
  {
    id: "works-snowboard",
    index: "10",
    cn: "雪粉飞溅",
    en: "Powder Burst",
    tone: "cyan",
    headline: "Snowboarding",
    headlineCn: "单板滑雪",
    note: "雪粉、风刃与失重的瞬间。极限运动的视觉切片。",
    noteEn: "Powder, wind, weightless beats. An action-sports cut.",
    brand: "致敬 Arc'teryx Alpha 硬壳美学",
    brandEn: "A tribute to the Arc'teryx Alpha hardshell aesthetic",
    duration: "00:57",
    coverSrc: "/covers/works-09.jpg",
    videoSrc: "/videos/snowboard.mp4",
  },
  {
    id: "works-acg",
    index: "11",
    cn: "复古未来",
    en: "Retro Future",
    tone: "orange",
    headline: "Ski Aesthetic",
    headlineCn: "滑雪美学",
    note: "头盔之上的世界。第一人称的速度与情绪。",
    noteEn: "From inside the helmet. First-person speed, first-person feel.",
    brand: "灵感来自 80s 复古未来 · 致敬 Oakley × Moncler 风格",
    brandEn: "Inspired by 80s retro-futurism · a nod to Oakley × Moncler",
    duration: "01:00",
    coverSrc: "/covers/works-10.jpg",
    videoSrc: "/videos/acg.mp4",
  },
  {
    id: "works-outdoor-portrait",
    index: "12",
    cn: "高原日光",
    en: "Alpine Light",
    tone: "fashion",
    headline: "Outdoor Portrait",
    headlineCn: "户外人像",
    note: "山野、风、光线。把户外感拍成人物气质。",
    noteEn: "Trail, wind, light. Outdoor air as personal presence.",
    brand: "灵感来自 Nike Trail 高原秋日美学",
    brandEn: "Inspired by Nike Trail high-alpine autumn aesthetics",
    duration: "00:21",
    coverSrc: "/covers/works-11.jpg",
    videoSrc: "/videos/outdoor-portrait.mp4",
  },
  {
    id: "works-architecture",
    index: "13",
    cn: "暮色咖啡馆",
    en: "Twilight Café",
    tone: "space",
    headline: "Space Aesthetic",
    headlineCn: "空间美学",
    note: "光、结构、暮色。把建筑拍成有呼吸感的场域。",
    noteEn: "Light, structure, dusk. Architecture that breathes.",
    brand: "灵感来自 Blue Bottle / % Arabica 精品咖啡空间美学",
    brandEn: "Inspired by Blue Bottle / % Arabica café-space aesthetics",
    duration: "02:08",
    coverSrc: "/covers/works-architecture.jpg",
    videoSrc: "/videos/architecture.mp4",
  },
];

export const aboutPillars = [
  {
    index: "01",
    label: "CONCEPT",
    cn: "创意先行",
    en: "Concept First",
    body: "从一句话开始。几小时之内，多种风格并排呈现。创意决策，第一次变得可见。",
    bodyEn: "One sentence in. Hours later, directions sit side by side. For the first time, the creative call is visible.",
  },
  {
    index: "02",
    label: "MOTION",
    cn: "动态影像",
    en: "Motion, Made",
    body: "品牌大片。社媒短片。产品发布。AI 生成，人工后期。气质与节奏，我们把关。",
    bodyEn: "Hero films. Social cuts. Product launches. AI-generated, hand-finished. We hold the mood and the rhythm.",
  },
  {
    index: "03",
    label: "BUDGET",
    cn: "成本可控",
    en: "Budget, Honest",
    body: "省下拍摄、棚景、特效与合成。同样的预算，更多版本，更多可能。",
    bodyEn: "No shoot. No set. No VFX comp. Same budget — more cuts, more options.",
  },
];

